/**
 * 3D Rotate Tool by YoFLA.com
 *
 * @author Matus Laco, www.yofla.com
 * @description Script for rotating images to provide a 3D look of an object
 * @sicne 06/2010
 * @updated 2014-08-18
 * @version 1.4.2
 * @homepage http://www.yofla.com/3d-rotate/
 *
 * @license : You many not delete/modify this license or authorship info
 * @license_type : 3DRTFLEXIPROWL
 * @licensed_to : Vlad Voiculescu PAXTEC SRL   Order Id: 4098
 * @authorized_domains : 
 *
 * 3rd Party licenses:
 * Wave Pre-loader: MIT (https://github.com/tobiasahlin/SpinKit)
 *
 */

var RotateTool="object"===typeof RotateTool?RotateTool:{instances:{},logLevel:"info,debug",isLogEnabled:!1,isInitialized:!1,isTouchDevice:!1,isSupportedBrowser:null,isFullscreenBrowserAPISupported:!1,isCustomEventSupported:!1,authorizedDomains:"",scriptVersion:"1.4.2",licenseType:"3DRTFLEXIPROWL",eventsTouchStart:{forMouse:"mousedown",forTouch:"touchstart"},eventsTouchEnd:{forMouse:"mouseup",forTouch:"touchend"},eventsTouchMove:{forMouse:"mousemove",forTouch:"touchmove"},
eventsMouseOver:{forMouse:"mouseover",forTouch:void 0},eventsMouseOut:{forMouse:"mouseout",forTouch:void 0},eventsMouseLeave:{forMouse:"mouseleave",forTouch:void 0},listeners:[],ON_IMAGE:"3drt_on_image",ROTATION_START:"3drt_rotation_start",ROTATION_STOP:"3drt_rotation_stop",ZOOM_START:"3drt_zoom_start",ZOOM_STOP:"3drt_zoom_stop",ZOOM_CHANGE:"3drt_zoom_change",ZOOM_RESET:"3drt_zoom_reset",PAN_START:"3drt_pan_start",PAN_STOP:"3drt_pan_stop",TURN_START:"3drt_turning_start",TURN_STOP:"3drt_turning_stop",
HOTSPOT_HOVER:"3drt_hotspot_hover",HOTSPOT_OPEN:"3drt_hotspot_open",PRELOADER_LOADED:"3drt_preloader_image_loaded",PRELOADER_PROGRESS:"3drt_preloader_progress",IMAGES_LOADED:"3drt_images_loaded",TOGGLE_ROTATE_MODE:"3drt_toggle_rotate_mode",TOGGLE_PAN_MODE:"3drt_toggle_pan_mode",MOUSEWHEEL_ZOOM:"3drt_mousewheel_zoom",CLICK_OBJECT:"3drt_click_object",BUTTON_PLAY_PAUSE_CLICK:"3drt_button_play_pause_click",BUTTON_ARROW_LEFT_CLICK:"3drt_button_arrow_left_click",BUTTON_ARROW_RIGHT_CLICK:"3drt_button_arrow_right_click",
BUTTON_FULLSCREEN_CLICK:"3drt_button_fullscreen_click",BUTTON_ZOOMSLIDER_CLICK:"3drt_button_zoomslider_click",BUTTON_ROTATE_CLICK:"3drt_button_toggle_rotate_click",BUTTON_PAN_CLICK:"3drt_button_toggle_pan_click",CONTEXMENU_SHOW:"3drt_contex-menu_show",zIndex:{images:5,preloaderImage:9,preloader:10,customLayer:15,clickPane:20,buttons:30,hotspots:40,toolTip:50,overlay:100,hotspotImage:110,hotspotTitle:120,customLogo:130,contexMenu:150,info:200},initialize:function(){this.isInitialized||(this.defaultGAevents=
[this.CLICK_OBJECT,this.BUTTON_PLAY_PAUSE_CLICK,this.BUTTON_ARROW_LEFT_CLICK,this.BUTTON_ARROW_RIGHT_CLICK,this.BUTTON_FULLSCREEN_CLICK,this.BUTTON_ZOOMSLIDER_CLICK,this.BUTTON_ROTATE_CLICK,this.BUTTON_PAN_CLICK,this.HOTSPOT_HOVER,this.HOTSPOT_OPEN,this.CONTEXMENU_SHOW,this.ZOOM_START],this.addPolyFills(),this.isSupportedBrowser=this.supportedBrowserCheck(),this.isTouchDevice="ontouchstart"in document.documentElement,this.isFullscreenBrowserAPISupported=this.fullscreenBrowserCheck(),this.isRunningInIframe=
this.isInIframe(),this.isCustomEventSupported=this.detectCustomEventSupport(),this.yofla_360_is_preview=!1,this.addDefaultStyleSheets(),window.addEventListener?window.addEventListener("load",this.onPageLoaded,!1):window.attachEvent("onload",this.onPageLoaded),this.addGlobalFunctions(),this.isInitialized=!0)},addDefaultStyleSheets:function(){var a;a="div.rotate-tool-instance{";a+="    background-color: white;";a+="    border: 1px solid silver;";a+="}";a+="img.rotate-tool-image";a+="{";a+="    max-width: none;";
a+="    vartical-align: none;";a+="    -moz-box-sizing: none;";a+="}";a+="div.rotate-tool-button";a+="{";a+="    width: 22px;";a+="\theight: 22px;";a+="    cursor: pointer;";a+="\tbackground-repeat: no-repeat;";a+="\tbackground-size: 44px 22px;";a+="}";a+="div.rotate-tool-button:hover";a+="{";a+="\tbackground-position: -22px;";a+="}";a+="div.rotate-tool-button-play{";a+="    left: 5px;";a+="    bottom: 5px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFFRUVLy8v//////8AJoZYjAAAADxJREFUGNNjCEUAhqxVQDD9PxD8pYy9QksLyD78GcLmArE/QNhMYLY9mM0AZvNjsJHVIOtFmEkldyL5HQDD7qVRB7C57QAAAABJRU5ErkJggg==);";
a+="}";a+="div.rotate-tool-button-left{";a+="    left: 32px;";a+="    bottom: 5px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFFhYWMDAw//////8AZLkVfgAAAEVJREFUGNNjCEUAhqxVQDD9PxD8JYO9CMy2B7ObQOw/EDYTiP0BzF7BwARkH2CwB7IXgNkMGGxkNch6UcxEtot8NyP5HQCCJ57LTpeIaAAAAABJRU5ErkJggg==);";a+="}";a+="div.rotate-tool-button-right{";a+="    left: 59px;";a+="    bottom: 5px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFFhYWMDAw//////8AZLkVfgAAAEVJREFUGNNjCEUAhqxVQDD9PxD8JYO9Asw+D2FrgdiHIWwuEPsAiL2CgQnIPsBgD2YzgNn8GGyEGmS9qGYi2UW+m5H8DgB2G6KpbvLpTAAAAABJRU5ErkJggg==);";
a+="}";a+="div.rotate-tool-button-up{";a+="    left: 86px;";a+="    bottom: 5px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFFhYWMDAw//////8AZLkVfgAAAEhJREFUGNNjCEUAhqxVQDD9PxD8JYO9AMzmB7MbtIDsP8xgNgMXkP2BAcRewcAEZB9gsAeyFzAwANkMDPzo6olhU+JOBBvJ7wAE1aC6h0oGfwAAAABJRU5ErkJggg==);";a+="}";a+="div.rotate-tool-button-down{";a+="    left: 113px;";a+="    bottom: 5px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFFhYWMDAw//////8AZLkVfgAAAERJREFUGNNjCEUAhqxVQDD9PxD8pZDdoAVk/2Emlr2AgQHIZmDgB7JXMDAB2QcY7EFqGLiA7A8MGHoXgO3ip9CdSH4HAPK5oLrk0HFkAAAAAElFTkSuQmCC);";
a+="}";a+="div.rotate-tool-button-fullscreen{";a+="    left: 5px;";a+="    bottom: 32px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAACVBMVEUAAAD//wD///+tfaOSAAAAX0lEQVQYV5WOIRKAMAwEQ2di0OUDqA6vqACP4P5Df5JBMfdKIlNRwapVdysS2Og0OFfnRWipVYVkKTPpDpzuia/7gup+09a2KyZ3oz3tUGgebv71uNl9xYbYFppHm4EPlIpSJ55rRFIAAAAASUVORK5CIIA=);";a+="}";a+="div.rotate-tool-button-toggle-rotate{";a+="    right: 10px;";a+="    bottom: 32px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWBAMAAABJS2P5AAAAD1BMVEUAAAAzMwAzMzP//wD///82WnNwAAAAlUlEQVQYGQXBAY2DUBAFwOnjC6iEDQrIKSBVjgQUNL8+YLmZ1woAAEYKoH9vgCcAAEAAAICgAWhAYAIwgUFPeqbQk54p4WBywcnkJi40Dm40TgEBICAolbVAqaxFiABEgEABUEC4AgfcgZPgwAWcuDEM/aXtbdFfHtsTdjBgAwthgB0WsDHwAeAPEAAAIAAAwGsFAAD/6Morwh2vPYAAAAAASUVORK5CIIA=);";
a+="}";a+="div.rotate-tool-button-toggle-pan{";a+="    right: 37px;";a+="    bottom: 32px;";a+="\tbackground-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAWAgMAAADGC5ZZAAAADFBMVEUAAAAwMDD//zP////69hx2AAAAkElEQVQYV2XPPQoCMRAF4ICNLMKeQ1vbQE7hbQSPkCssbLPmGjZiM92cIzht4Pkmgr+v+pp5vAmHd8IJjBbm/OPaPbirrOh13dEyRuhS7fa0uK+0SdxriXbZdptb6A2a6ZRBH1lpmkeAboBoFjTeJveMbnEvLyf33fvdJXU3NO7J8A1I7vnfIdBTGL7/+vj9AdURpbIgQpWIAAAAAElFTkSuQmCC);";a+="}";a+="div.rotate-tool-zoomslider{";a+="    width: 110px;";
a+="    height: 22px;";a+="    right: 10px;";a+="    bottom: 5px;";a+="    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAG4AAAAWCAYAAAAhKqlXAAAAnElEQVRo3u3YMQqAIBSAYZ2lRhWiK+juRTuXV+kCZdEURE3xXv0/iA5C8D5wyBpSmWUEwBFw/y2l1LVtPNZwcZ6AE4binOtDCCbGaLz3+34+l1Jm4IShtDu338o581RKQ3kScAJRgFOK8nm4r6Kohvszilg4UATCgSIQDhSBcKAohGtoyzZwUBTC1VqZBnD0Ghyj0Bc/mYEj4Oi2FZMURCKzQ84gAAAAAElFTkSuQmCC);";a+="    background-repeat: no-repeat;";a+="}";a+="div.rotate-tool-zoomslider-handle{";a+="    width: 13px;";
a+="    height: 22px;";a+="    left: 0px;";a+="    bottom: 0px;";a+="    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAWAgMAAACj5mQmAAAABGdBTUEAALGPC/xhBQAAAAxQTFRFLi4uLi4u//IA////rlRNtQAAAAF0Uk5TllmK7hcAAAAdSURBVAjXYxANDWUNDXVgqP//P2rVqgmDloa6EwC+zWH5+5JnmgAAAABJRU5ErkJggg==);";a+="    background-repeat: no-repeat;";a+="\tbackground-size: 26px 22px;";a+="}";a+="div.rotate-tool-zoomslider-handle:hover{";a+="\tbackground-position: -13px;";a+="}";a+="div.rotate-tool-spacer{";
a+="    background-image: url(https://www.yofla.com/cdn/rotatetool/spacer.gif);";a+="    background-repeat: no-repeat";a+="}";a+="div.rotate-tool-hotspot-default{";a+="    width: 22px;";a+="    height: 22px;";a+="    border-radius: 14px;";a+="    border: 2px solid white;";a+="    opacity: 0.75;";a+="    filter: Alpha(Opacity=75);";a+="    background-color: deepskyblue;";a+="}";a+=".rotate-tool-unselectable{";a+="    -moz-user-select: none;";a+="    -webkit-user-select: none;";a+="    -ms-user-select: none;";
a+="    user-select: none;";a+="    -webkit-user-drag: none;";a+="    user-drag: none;";a+="}";a+="\t\t.yp_wave {";a+="\t\t\tmargin: 100px auto;";a+="\t\t\twidth: 50px;";a+="\t\t\theight: 30px;";a+="\t\t\ttext-align: center;";a+="\t\t\tfont-size: 10px;";a+="\t\t}";a+="\t\t.yp_wave > div {";a+="\t\t\tbackground-color: #333;";a+="\t\t\theight: 100%;";a+="\t\t\twidth: 6px;";a+="\t\t\tdisplay: inline-block;";a+="\t\t\t-webkit-animation: stretchdelay 1.2s infinite ease-in-out;";a+="\t\t\tanimation: stretchdelay 1.2s infinite ease-in-out;";
a+="\t\t}";a+="\t\t.yp_wave .rect2 {";a+="\t\t\t-webkit-animation-delay: -1.1s;";a+="\t\t\tanimation-delay: -1.1s;";a+="\t\t}";a+="\t\t.yp_wave .rect3 {";a+="\t\t\t-webkit-animation-delay: -1.0s;";a+="\t\t\tanimation-delay: -1.0s;";a+="\t\t}";a+="\t\t.yp_wave .rect4 {";a+="\t\t\t-webkit-animation-delay: -0.9s;";a+="\t\t\tanimation-delay: -0.9s;";a+="\t\t}";a+="\t\t.yp_wave .rect5 {";a+="\t\t\t-webkit-animation-delay: -0.8s;";a+="\t\t\tanimation-delay: -0.8s;";a+="\t\t}";a+="\t\t@-webkit-keyframes stretchdelay {";
a+="\t\t\t0%, 40%, 100% { -webkit-transform: scaleY(0.4) }";a+="\t\t20% { -webkit-transform: scaleY(1.0) }";a+="\t\t}";a+="\t\t@keyframes stretchdelay {";a+="\t\t\t0%, 40%, 100% {";a+="\t\t\t\ttransform: scaleY(0.4);";a+="\t\t\t-webkit-transform: scaleY(0.4);";a+="\t\t} 20% {";a+="\t\t\ttransform: scaleY(1.0);";a+="\t\t\t-webkit-transform: scaleY(1.0);";a+="\t\t\t}";a+="\t\t}";a+="span.rotate-tool-tooltip{";a+="    font-family: sans-serif;";a+="    font-size: 13px;";a+="    color: #0c0c0c;";a+="    padding: 5px;";
a+="    opacity: 0.85;";a+="    filter: Alpha(Opacity=85);";a+="    border-radius: 5px;";a+="    border: 1px solid gray;";a+="    background-color: rgba(230,230,230,0.5);";a+="}";a+="ul.rotate-tool-contex-menu {";a+="border:0px solid #666;";a+="min-width:150px;";a+="max-width:350px;";a+="list-style:none;";a+="padding:0;";a+="margin:0;";a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li {";a+="text-align:left;";a+="padding:3px 10px 3px 5px;";a+="margin:0;";a+="cursor:pointer;";a+='font-family: "Lucida Grande", Verdana, Arial, "Bitstream Vera Sans", sans-serif;';
a+="text-decoration:none;";a+="color:#fff;";a+="font-size:12px;";a+="border-top:1px solid #fff;";a+="border-left:1px solid #fff;";a+="border-bottom:1px solid #999;";a+="border-right:1px solid #999;";a+="background-color: rgba(0,0,0,.7);";a+="}";a+="ul.rotate-tool-contex-menu li.selected,";a+="ul.rotate-tool-contex-menu li:hover {";a+="color:#fff;";a+="background-color: rgba(56,117,215,.7);";a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li.selected:hover {";a+="color:#333;";a+="background-color:#eee;";
a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li.disabled,";a+="ul.rotate-tool-contex-menu li:hover.disabled {";a+="background-color: #eee;";a+="color:#999;";a+="cursor:pointer;";a+="}";var d=document.getElementsByTagName("head")[0],f=document.createElement("style");f.type="text/css";f.styleSheet?f.styleSheet.cssText=a:f.appendChild(document.createTextNode(a));d.appendChild(f)},onPageLoaded:function(){RotateTool.execRotateTool()},execRotateTool:function(){if(!1!=RotateTool.isObjectEmpty(RotateTool.instances))for(var a=
document.querySelectorAll("[data-rotate-tool]"),d,f,b,c,g=0;g<a.length;g++){d=a[g];f=d.getAttribute("data-rotate-tool");c=d.getAttribute("id");c||(c="rotate-tool-instance-id-"+Math.round(1E4*Math.random()),d.setAttribute("id",c));try{b=this.parseJSON(f)}catch(k){this.reportUserError('Error parsing data in element with id "'+c+'" : '+k);break}d={target:c,path:b.path,id:b.id,mode:b.mode,configFile:b.configFile,themeUrl:b.themeUrl,gaData:b.gaData?b.gaData:{}};this.add(d)}},createInstance:function(a){if("undefined"===
typeof this.instances[a.target]&&(this.instances[a.target]=this.rotateToolFactory(a),"function"===typeof window.yofla_rotateToolInstanceInitialized))try{window.yofla_rotateToolInstanceInitialized(a.target)}catch(d){}},createPopupLink:function(a){document.getElementById(a.target)},add:function(a){this.isInitialized||this.initialize();var d=this.validateRotationData(a);!0===d?"popup"==a.mode?this.createPopupLink(a):this.createInstance(a):this.reportUserError(d)},get:function(a){return a?(a=this.instances[a])?
a:null:this.getAnonymousInstance()},getAnonymousInstance:function(){var a,d;for(d in this.instances){a=this.instances[d];break}return a},reportUserError:function(a){alert("RotateTool Error: "+a)},log:function(a,d){if("undefined"!==typeof console&&this.isLogEnabled){-1<this.logLevel.indexOf(a)&&console.log(d);var f=document.getElementById("logdiv");f&&(f.innerHTML=d)}},validateRotationData:function(a){return a.target?!0:"Target not defined!"},rotateToolFactory:function(a){var d={elementId:a.target,
target:document.getElementById(a.target),path:a.path,configFile:a.configFile?a.configFile:"config.js",isConfigJsLoaded:!1,productId:a.id,themeUrl:a.themeUrl,settings:{},originalTargetWidth:null,originalTargetHeight:null,originalTargetRatio:null,targetWidth:null,targetHeight:null,targetRation:null,zIndex:{},buttons:{},vSteps:null,hSteps:null,imageNodes:null,rotateIntervalDuration:null,rotateInterval:null,rotateImages:[],imagesGrid:[],lastImgH:null,lastImgV:null,newImgH:null,newImgV:null,dx:0,dy:0,
previousDx:0,isRotating:!1,wasRotating:!1,currentImage:null,previousImage:null,rotateOnceCounter:0,isZoomed:!1,scaleInPercent:100,relativeX:0.5,relativeY:0.5,isRotationWhenZoomed:!1,dragInterval:null,touchStart:null,touchMove:null,touchMovePrevious:null,touchMovePreviousDrag:null,lastYatDyChange:null,touchEnd:null,mouseWheelZooms:!1,imageLoadErrorsString:"",imageLoadErrorCount:0,imagesToLoad:null,imagesLoaded:null,imagesProcessed:null,isImagesLoaded:!1,preloader:null,usingSmallImages:null,hotspotInstances:null,
activeHotspot:null,hotspotOverlay:null,hotspotImage:null,daggedObject:null,clickPaneTouchMoveReference:null,clickPaneTouchEndReference:null,requestRescaleFlag:!1,mouseWheelCounter:0,clickPane:null,sliderHandle:null,handleMaxX:null,infoPanel:null,isGAenabled:a.gaData.isEnabled&&"true"==a.gaData.isEnabled.toLowerCase(),gaEnabledEvents:a.gaData.enabledEvents instanceof Array?a.gaData.enabledEvents:RotateTool.defaultGAevents,gaTrackingId:a.gaData.trackingId,gaCategory:a.gaData.category,gaLabel:a.gaData.label,
setLevel:function(a){!1!==this.isImagesLoaded&&(this.lastImgV=a,a=this.dx,this.dx=this.dy=0,this.showNextImage(),this.dx=a)},initialize:function(){if(this.target){this.path=RotateTool.fixPathVariable(this.path);var f=this.path+this.configFile;this.zIndex=RotateTool.zIndex;this.setTargetStyles();this.loadStyles(this.themeUrl);this.setTargetDimensions();this.gaCategory=this.gaCategory&&""!=this.gaCategory?this.gaCategory:"YOFLA_360";var b=this.productId?this.productId:this.elementId;this.gaLabel=this.gaLabel&&
""!==this.galabel?this.gaLabel:"YOFLA_360_"+b;RotateTool.loadScript(f,this.configJsLoaded,this)}else RotateTool.reportUserError("Could not locate target element with id:"+a.target)},setTargetStyles:function(){this.target.style.position="relative";this.target.style.minWidth="150px";this.target.style.minHeight="150px";this.target.style.overflow="hidden";this.target.className="rotate-tool-instance";this.target.className+=" rotate-tool-spacer";this.target.className+=" rotate-tool-unselectable";this.originalTargetWidth=
this.target.clientWidth;this.originalTargetHeight=this.target.clientHeight;this.originalTargetRatio=this.originalTargetWidth/this.originalTargetHeight;this.updateTargetStyles()},updateTargetStyles:function(){RotateTool.isRunningInIframe?(this.target.style.width="100%",this.target.style.height="100%"):document.documentElement.clientWidth<this.originalTargetWidth?(this.target.style.width=document.documentElement.clientWidth+"px",this.target.style.height=Math.floor(document.documentElement.clientWidth/
this.originalTargetRatio)+"px"):(this.target.style.width=this.originalTargetWidth+"px",this.target.style.height=this.originalTargetHeight+"px")},setTargetDimensions:function(){this.targetWidth=Math.min(this.target.clientWidth,document.documentElement.clientWidth);this.targetHeight=Math.max(200,this.target.clientHeight);this.targetRatio=this.targetWidth/this.targetHeight},loadStyles:function(a){var b=document;a="undefined"===typeof a?this.path+"assets/styles.css":RotateTool.fixPathVariable(a)+"styles.css";
if(!b.getElementById("rotate-tool-styles")){var c=b.getElementsByTagName("head")[0],b=b.createElement("link");b.id="rotate-tool-styles";b.rel="stylesheet";b.type="text/css";b.href=a;b.media="all";c.appendChild(b)}},setInfo:function(){var a=this.createInfoIcon();this.target.appendChild(a);var b=this.createInfoPanel();this.target.appendChild(b);this.infoPanel=b;var c=this,g=function(){c.showInfoPanel(b)};RotateTool.addClickOrTouchListener(a,{forTouch:"touchstart",forMouse:"mouseover"},function(b){a.style.opacity=
1;a.style.filter="alpha(Opacity=100)"});RotateTool.addClickOrTouchListener(a,{forTouch:"touchend",forMouse:"mouseout"},function(b){a.style.opacity=0.5;a.style.filter="alpha(Opacity=50)";RotateTool.isTouchDevice&&g()});RotateTool.addClickOrTouchListener(a,{forTouch:void 0,forMouse:"click"},g)},createInfoIcon:function(){var a=document.createElement("div");a.style.position="absolute";a.style.top="5px";a.style.left="5px";a.style.width="25px";a.style.height="25px";a.style.cursor="pointer";a.style.border=
"0px";a.style.zIndex=this.zIndex.info;a.style.backgroundImage="url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAMAAADzN3VRAAAAaVBMVEUAAADq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urm39/i1NTeycnbvr3TpqXPmZjLjIrHf33EcG7BYl+9Uk65QDq1LCKxGQIgeu/UAAAAInRSTlMAARMVFzAyPVRqi4ysrrK9wsvP2ubo6evt8PLz9ff4+vz9cPxJuAAAANBJREFUKM99UtkOhCAMrDfeit31dpH//8gVBKqJcZ5aJqXTaQFOhCyreMerjIVwRZDWaFGnARFxgVcUsSWSFu9ok5OIuHn4ztu+6ohHivBLQ4y7PNDruPQBvNT+oYnFJKkHQWOZWcrfaJMmAIbPYJBTMi7CtDmQQ2XDQag+7rsK+E2AHGzKobPhJEj0gY5qcFMMUo3rg6pGIPUhbapkQ9Lm5ukVM1/mcR4MumYgD5xvk1a9km/Oa80Io1p57fbTC7mNH7zs52WnL3fwcjuP9/YHpzIqZ7oB1g0AAAAASUVORK5CYII=')";
a.style.opacity=0.5;a.style.filter="alpha(Opacity=0.5)";return a},createInfoPanel:function(){var a=document.createElement("div");a.style.position="absolute";a.style.display="none";a.style.width="120px";a.style.height="60px";a.style.margin="auto";a.style.padding="10px";a.style.borderRadius="10px";a.style.borderWidth="1px";a.style.borderColor="#000000";a.style.zIndex=this.zIndex.info+1;a.style.fontFamily="sans-serif";a.style.fontSize="14px";a.style.color="black";a.style.lineHeight="20px";a.style.backgroundColor=
"silver";a.innerHTML='3D Rotate Tool<br/>by<br/><a href="http://www.yofla.com/3d-rotate/?ref=playerFree">YoFLA.com</a>';RotateTool.addClickOrTouchListener(a,{forTouch:"touchend",forMouse:"mouseup"},RotateTool.bind(this,this.hideInfoPanel));return a},showInfoPanel:function(a){if("block"==this.infoPanel.style.display)this.hideInfoPanel();else{var b=parseInt(a.style.width,10),c=parseInt(a.style.height,10);b<=this.targetWidth&&c<=this.targetHeight&&(a.style.display="block",a.style.left="30px",a.style.top=
"30px")}},hideInfoPanel:function(){this.infoPanel&&(this.infoPanel.style.display="none")},addContexMenu:function(){this.addContexMenuListener();this.addContexMenuContainer();this.setContexMenuItems(this.getContexMenuItems())},getContexMenuItems:function(){var a=[],b={title:"Disable this menu",action:"CONTEXMENU_DISABLE",data:null},c=this.getCustomContexMenuItems();0<c.length&&(a=c.concat(a));if("3DRTFLEXIPRO"==RotateTool.licenseType||"3DRTFLEXIPROWL"==RotateTool.licenseType)c=RotateTool.getCurrentDomain().toLocaleLowerCase(),
0<c.length&&0>RotateTool.authorizedDomains.indexOf(c)&&"localhost"!==c&&a.unshift({title:"Domain not authorized!",action:"URL_OPEN",data:"http://www.yofla.com/3d-rotate/support/domain-not-authorized/"});0<a.length&&a.push(b);return a},getCustomContexMenuItems:function(){var a=[],b,c;if(this.settings.custom&&this.settings.custom.contexMenu)for(b=this.settings.custom.contexMenu.items,i=0;i<b.length;i++)(c=b[i])&&c.title&&0<c.title.length&&a.push(c);return a},addContexMenuListener:function(){var a=this;
this.funcRefContexMenuShow=function(b){b.preventDefault();a.showContexMenu(b)};this.funcRefContexMenuShowIE=function(){window.event.returnValue=!1;a.showContexMenu(window.event)};this.target.addEventListener?this.target.addEventListener("contextmenu",this.funcRefContexMenuShow,!1):this.target.attachEvent("oncontextmenu",this.funcRefContexMenuShowIE)},disableContexMenu:function(){this.target.addEventListener?this.target.removeEventListener("contextmenu",this.funcRefContexMenuShow,!1):this.target.detachEvent("oncontextmenu",
this.funcRefContexMenuShowIE)},addContexMenuContainer:function(){this.contexMenu=document.createElement("ul");this.contexMenu.style.zIndex=this.zIndex.contexMenu;this.contexMenu.style.position="absolute";this.contexMenu.style.display="none";this.contexMenu.style.left="100px";this.contexMenu.style.top="100px";this.contexMenu.className="rotate-tool-contex-menu";this.target.appendChild(this.contexMenu);RotateTool.addClickOrTouchListener(this.contexMenu,RotateTool.eventsMouseLeave,RotateTool.bind(this,
this.hideContexMenu))},setContexMenuItems:function(a){this.contexMenu.innerHTML="";for(var b=this,c,g,d,e=0;e<a.length;e++)c=document.createElement("li"),g=a[e],d=function(a){return function(f){b.onContexMenuItemSelected(f,a)}}(g),c.innerHTML=g.title,RotateTool.addClickOrTouchListener(c,{forMouse:"click"},d),this.contexMenu.appendChild(c)},onContexMenuItemSelected:function(a,b){this.hideContexMenu();switch(b.action){case "URL_OPEN":window.open(b.data,"_blank");break;case "CONTEXMENU_DISABLE":this.disableContexMenu()}},
showContexMenu:function(a){this.dispatchEvent(RotateTool.CONTEXMENU_SHOW);a=RotateTool.getLocalMousePosition(a);isNaN(a.x)||isNaN(a.y)||(this.contexMenu.style.display="block",this.contexMenu.style.left=a.x+"px",this.contexMenu.style.top=a.y+"px")},hideContexMenu:function(){this.contexMenu&&(this.contexMenu.style.display="none")},configJsLoaded:function(){if(!this.isConfigJsLoaded){this.isConfigJsLoaded=!0;RotateTool.yofla_360_is_preview="undefined"===typeof yofla_360_is_preview?!1:!0;var a;try{a=
eval("productRotationData_"+this.productId)}catch(b){try{a=eval("RotationData_"+this.productId)}catch(c){try{a=eval("RotationData")}catch(g){return RotateTool.reportUserError("Error evaluating config.js!"),!1}}}if(void 0===a)return RotateTool.reportUserError("Error accessing settings in config.js!"),!1;try{this.parseSettings(a)}catch(d){RotateTool.reportUserError("Error parsing settings, maybe a typo? Error: "+d);return}RotateTool.isSupportedBrowser?(this.target.innerHTML="",this.addWindowResizeListener(),
this.initCustomLogo(),this.addContexMenu(),this.initHotspots(),this.initRotation()):this.reportBrowserNotSupported()}},parseSettings:function(a){this.settings.rotation={rotatePeriod:a.settings.rotation.rotatePeriod,rotateOnStart:"true"==a.settings.rotation.rotate,rotateDirection:a.settings.rotation.rotateDirection,bounce:a.settings.rotation.bounce,rotateOnce:"once"==a.settings.rotation.rotate,multilevel:{}};try{this.settings.rotation.multilevel.verticalSensitivity=a.settings.rotation.multilevel.verticalSensitivity}catch(b){this.settings.rotation.multilevel.verticalSensitivity=
5}this.settings.preloader={type:"undefined"===typeof a.settings.preloader.type?"default":a.settings.preloader.type,color1:"undefined"===typeof a.settings.preloader.color1?"#333333":a.settings.preloader.color1,image:"undefined"===typeof a.settings.preloader.image?"first":a.settings.preloader.image};this.settings.userInterface={showTogglePlayButton:a.settings.userInterface.showTogglePlayButton,showArrows:a.settings.userInterface.showArrows,showToggleFullscreenButton:a.settings.userInterface.showToggleFullscreenButton,
showToggleRotateButton:a.settings.userInterface.showToggleRotateButton,showZoomSlider:a.settings.userInterface.showZoombar};this.settings.control={maxZoom:a.settings.control.maxZoom,dragSpeed:a.settings.control.dragSpeed,reverseDrag:a.settings.control.reverseDrag,rotateOnMouseHover:a.settings.control.rotateOnMouseHover,clickUrl:a.settings.control.clickUrl,clickUrlTarget:a.settings.control.clickUrlTarget,mouseWheelZooms:a.settings.control.mouseWheelZooms};this.settings.hotspots=a.hotspots;this.hSteps=
this.imagesToLoad=a.images.length;this.vSteps=1;try{this.vSteps=a.settings.rotation.multilevel.verticalSteps}catch(c){}"undefined"===typeof this.vSteps&&(this.vSteps=1);this.hSteps=this.imagesToLoad/this.vSteps;this.imageNodes=a.images;this.settings.hotspots=a.hotspots;this.settings.custom=a.custom},addWindowResizeListener:function(){var a=this;this.resizeListenerReference=function(b){a.windowResizeListener(b)};RotateTool.addEventSimple(window,"resize",this.resizeListenerReference)},initRotation:function(){this.showPreloaderImage(this.settings.preloader.image,
this.generateImages)},showPreloaderImage:function(a,b){var c;if(isNaN(a))switch(a){case "first":c=this.path+this.imageNodes[0].src;this.createPreloaderImage(c,b);break;case "splash":c=this.path+"splash.jpg";this.createPreloaderImage(c,b);break;case "splash.png":c=this.path+"splash.png";this.createPreloaderImage(c,b);break;default:b.apply(this)}else c=parseInt(a),c<this.imageNodes.length?(c=this.path+this.imageNodes[c].src,this.createPreloaderImage(c,b)):b.apply(this)},createPreloaderImage:function(a,
b){var c=document.createElement("img");this.target.appendChild(c);c.className="rotate-tool-preloader-image";c.style.position="absolute";c.style.display="block";c.style.visibility="hidden";c.style.zIndex=this.zIndex.preloaderImage;c.onload=this.preloaderImageLoaded.apply(this,[c,b]);c.onerror=null;c.src=a;this.preloaderImage=c},preloaderImageLoaded:function(a,b){var c=this;return function(){c.processLoadedPreloaderImage(a,b)}},processLoadedPreloaderImage:function(a,b){this.dispatchEvent(RotateTool.PRELOADER_LOADED);
a.scaled=!1;a.ratio=a.width/a.height;a.originalWidth=a.width;a.originalHeight=a.height;this.setScale(100,a);a.style.visibility="visible";b.apply(this)},generateImages:function(){this.addPreloader(this.settings.preloader.type);for(var a=0,b=0;b<this.imagesToLoad;b++){var c,g,d;c=this.path+this.imageNodes[b].src;g=this.imageNodes[b].srcLarge?this.path+this.imageNodes[b].srcLarge:!1;d=this.imageNodes[b].srcSmall?this.path+this.imageNodes[b].srcSmall:!1;var e=document.createElement("img");e.id="rotate-image-"+
b;e.className="rotate-tool-image";e.fileName=RotateTool.baseName(c);this.rotateImages[b]=e;void 0===this.imagesGrid[a]&&(this.imagesGrid[a]=[]);this.imagesGrid[a].push(b);e.data=this.imageNodes[b];e.hotspots=this.processImageDataHotspots(e.data.hotspots);e.srcNormal=c;e.srcLarge=g;e.srcSmall=d;e.style.display="block";e.style.webkitTransform="translateZ(0)";e.style.MozTransform="translateZ(0)";e.style.msTransform="translateZ(0)";e.style.OTransform="translateZ(0)";e.style.transform="translateZ(0)";
e.style.visibility="hidden";e.onload=this.imageLoaded.apply(this,[e]);e.onerror=this.imageError.apply(this,[e]);d?(e.src=d,this.usingSmallImages=!0):(e.src=c,this.usingSmallImages=!1);0===(b+1)%this.hSteps&&a++}},addPreloader:function(a){switch(a){case "wave":RotateTool.browserSupportsCSSProperty("animation")?this.preloader=RotateTool.wavePreloader(this.elementId,this.settings.preloader.color1):this.preloader=RotateTool.defaultPreloader(this.elementId,this.settings.preloader.color1);break;default:this.preloader=
RotateTool.defaultPreloader(this.elementId,this.settings.preloader.color1)}},processImageDataHotspots:function(a){var b=null;if(!RotateTool.isObjectEmpty(a)){var b=[],c;for(c in a){var g={};g.id=a[c].id;g.rx=a[c].rx;g.ry=a[c].ry;b.push(g)}}return b},imageLoaded:function(a){var b=this;return function(){b.imagesLoaded++;b.processLoadedImage(a);b.increaseImagesProcessedCount()}},imageNormalLoaded:function(a){var b=this;return function(){b.processLoadedImageNormal(a)}},imageError:function(a){var b=this;
return function(){b.imageLoadErrorsString+=a.src+"\n";b.imageLoadErrorCount+=1;b.increaseImagesProcessedCount()}},increaseImagesProcessedCount:function(){this.imagesProcessed++;this.updatePreloader();this.checkImagesProcessed()},checkImagesProcessed:function(){if(this.imagesProcessed==this.imagesToLoad){this.destroyPreloader();if(this.imagesLoaded==this.imagesToLoad)this.onAllImagesSuccesfullyLoaded();this.preloaderImage&&(this.preloaderImage.style.display="none")}},updatePreloader:function(){var a=
Math.round(100*(this.imagesProcessed/this.imagesToLoad));this.preloader&&this.preloader.update&&this.preloader.update(a);this.dispatchEvent(RotateTool.PRELOADER_PROGRESS,parseInt(a))},destroyPreloader:function(){this.preloader&&this.preloader.destroy&&this.preloader.destroy()},processLoadedImage:function(a){this.target.appendChild(a);a.style.position="absolute";a.style.cursor="pointer";a.style.zIndex=this.zIndex.images;a.style.overflow="hidden";a.scaled=!1;a.ratio=a.width/a.height;a.originalWidth=
a.width;a.originalHeight=a.height;a.onload=null;a.style.visibility="hidden"},processLoadedImageNormal:function(a){var b=this.rotateImages[a.id];b.scaled=!1;b.onload=null;b.src=a.src},onAllImagesSuccesfullyLoaded:function(){this.dispatchEvent(RotateTool.IMAGES_LOADED,this.imagesLoaded);this.isImagesLoaded=!0;if("function"===typeof window.rotateToolInstanceLoaded)try{window.rotateToolInstanceLoaded(this.elementId)}catch(a){}if("function"===typeof window.yofla_rotateToolInstanceLoaded)try{window.yofla_rotateToolInstanceLoaded(this.elementId)}catch(b){}this.onImagesInitialized()},
initLoadedImages:function(){for(var a=0;a<this.rotateImages.length;a++);this.onImagesInitialized()},hideAllImages:function(){for(var a=0;a<this.rotateImages.length;a++)this.rotateImages[a].style.visiblity="hidden"},onImagesInitialized:function(){this.customLayer=document.createElement("div");this.customLayer.className="rotate-tool-custom-layer";this.customLayer.style.zIndex=this.zIndex.customLayer;this.target.appendChild(this.customLayer);this.addControls();this.initRotationVariables();this.setFirstImage();
this.showNextImage();(this.settings.rotation.rotateOnStart||this.settings.rotation.rotateOnce)&&this.startRotation();this.usingSmallImages&&setTimeout(RotateTool.bind(this,this.loadNormalImages),150)},setFirstImage:function(){var a=this.settings.preloader.image,b;"number"==typeof a&&(1==this.vSteps?a<this.hSteps&&(this.lastImgH=a-this.dx):(b=a%this.hSteps,a=Math.floor(a/this.hSteps),this.lastImgH=b-this.dx,this.lastImgV=a,this.dy=0))},loadNormalImages:function(){for(var a=0;a<this.rotateImages.length;a++){var b=
document.createElement("img");b.id=a;b.onload=this.imageNormalLoaded.apply(this,[b]);b.src=this.rotateImages[a].srcNormal}},initRotationVariables:function(){this.rotateIntervalDuration=1E3*this.settings.rotation.rotatePeriod/this.hSteps;this.lastImgH=null;this.newImgV=this.lastImgV=this.newImgH=0;this.dx=this.settings.rotation.rotateDirection;this.dy=0},initCustomLogo:function(){var a,b,c;try{a=this.settings.custom.logo.imageUrl,b=this.settings.custom.logo.linkUrl,c=this.settings.custom.logo.linkTarget}catch(g){}"undefined"!==
typeof a&&this.addCustomLogo(a,b,c)},addCustomLogo:function(a,b,c){var g,d;try{g=this.settings.custom.logo.imagePosition.left,d=this.settings.custom.logo.imagePosition.top}catch(e){d=g=5}var h=document.createElement("img");h.className="rotate-tool-custom-logo";h.style.zIndex=this.zIndex.customLogo;h.style.position="absolute";h.style.left=g+"px";h.style.top=d+"px";this.target.appendChild(h);g=this.path+a;0==a.indexOf("http")&&(g=a);h.src=g;b&&(c||(c="_blank"),RotateTool.addClickOrTouchListener(h,{forTouch:"touchend",
forMouse:"click"},function(){return function(){window.open(b,c)}}()))},initHotspots:function(){var a=this.settings.hotspots;if(a){this.hotspotInstances={};for(var b in a)this.initHotspotInstance(a[b])}},initHotspotInstance:function(a){var b=document.createElement("div");b.initialized=!1;b.data=a;b.style.display="none";b.style.position="absolute";b.style.cursor="pointer";b.style.zIndex=this.zIndex.hotspots;b.loaded=!1;b.id=a.id;if(a.icon.className)b.className=b.className+" "+a.icon.className;else if(a.icon.src){var c=
document.createElement("img");c.src=this.path+a.icon.src;b.appendChild(c);b.image=c}else b.className+=" rotate-tool-hotspot-default";a.position&&(b.isFixed=!0,this.positionFixedHotspot(b));this.target.appendChild(b);this.addHotspotEvents(b,a);this.hotspotInstances[a.id]=b},positionFixedHotspot:function(a){var b=a.data;b.position.top&&(a.style.top=b.position.top+"px");b.position.left&&(a.style.left=b.position.left+"px");b.position.right&&(a.style.right=b.position.right+"px");b.position.bottom&&(a.style.bottom=
b.position.bottom+"px")},addHotspotEvents:function(a,b){var c=this,g=a;a.image&&(g=a.image,g.data=a.data);RotateTool.addClickOrTouchListener(g,RotateTool.eventsTouchStart,function(){c.hotspotTouchStartListener(b)});RotateTool.addClickOrTouchListener(g,RotateTool.eventsTouchEnd,function(){c.hotspotTouchEndListener(b)});RotateTool.addClickOrTouchListener(g,RotateTool.eventsMouseOver,RotateTool.bind(this,this.hotspotMouseOverListener));RotateTool.addClickOrTouchListener(g,RotateTool.eventsMouseOut,RotateTool.bind(this,
this.hotspotMouseOutListener))},hotspotMouseOverListener:function(a){if(a&&a.target){var b=a.target.data;this.dispatchEvent(RotateTool.HOTSPOT_HOVER);b&&b.title&&this.showToolTip(a.target,b.title.text)}},hotspotMouseOutListener:function(a){this.getToolTip().hide()},showToolTip:function(a,b,c){this.getToolTip().show(a,b,c)},getToolTip:function(){this.toolTip||(this.toolTip=this.createToolTip());return this.toolTip},createToolTip:function(){var a=this,b={createDom:function(){this.toolTipTarget=document.createElement("span");
this.toolTipTarget.className="rotate-tool-tooltip";this.toolTipTarget.style.position="absolute";this.toolTipTarget.style.zIndex=a.zIndex.toolTip;a.target.appendChild(this.toolTipTarget)},show:function(b,g,d){var e;this.toolTipTarget.innerHTML=g;this.toolTipTarget.style.display="inline";this.toolTipTarget.style.MozTransition="opacity 0.4s ease-in-out";this.toolTipTarget.style.WebkitTransition="opacity 0.4s ease-in-out";this.toolTipTarget.style.opacity=1;b instanceof Array&&2==b.length?(g=b[0],e=b[1],
b=g+10):("IMG"==b.tagName&&(b=b.parentNode),e=b.offsetTop-0.3*this.toolTipTarget.offsetHeight,g=b.offsetLeft,b=b.offsetWidth+g+10);this.toolTipTarget.style.top=e+"px";e=this.toolTipTarget.offsetWidth;b+e>a.target.offsetWidth&&(b=g-e-5);this.toolTipTarget.style.left=b+"px";clearTimeout(this.toolTipTimeoutId);d&&(d=parseInt(d),setTimeout(RotateTool.bind(this,this.hide),d))},hide:function(){this.toolTipTarget.style.MozTransition="opacity 0.3s ease-in-out";this.toolTipTarget.style.WebkitTransition="opacity 0.3s ease-in-out";
this.toolTipTarget.style.opacity=0;this.toolTipTimeoutId=setTimeout(RotateTool.bind(this,this.onHideCompleted),300)},onHideCompleted:function(){this.toolTipTarget.style.display="none"},initialize:function(){this.createDom()}};b.initialize();return b},hotspotTouchStartListener:function(a){this.activeHotspot=a.id;RotateTool.isTouchDevice&&(this.executeHotspot(a),this.activeHotspot=null)},hotspotTouchEndListener:function(a){RotateTool.isTouchDevice||null===this.activeHotspot||this.activeHotspot!=a.id||
(this.executeHotspot(a),this.activeHotspot=null)},executeHotspot:function(a){this.stopRotation();this.dispatchEvent(RotateTool.HOTSPOT_OPEN);RotateTool.isObjectEmpty(a.image)?RotateTool.isObjectEmpty(a.javascript)?RotateTool.isObjectEmpty(a.url)||this.executeUrlHotspot(a.url):this.executeJavascriptHotspot(a.javascript):this.executeImageHotspot(a.image)},executeJavascriptHotspot:function(a){var b=a.command;a=a.attribute;try{eval(b+'("'+a+'");')}catch(c){RotateTool.reportUserError(c)}},executeUrlHotspot:function(a){var b=
a.src;a=a.target;b&&(a||(a="_top"),window.open(b,a))},executeImageHotspot:function(a){this.createImageHotspotOvelay();this.loadHotspotImage(a)},createImageHotspotOvelay:function(){var a=this.targetWidth,b=this.targetHeight,c=document.createElement("div");c.style.width=a+"px";c.style.height=b+"px";c.style.background="black";c.style.opacity="0.65";c.style.filter="alpha(Opacity=65)";c.style.display="block";c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.cursor="pointer";c.style.zIndex=
this.zIndex.overlay;this.target.appendChild(c);var d=document.createElement("div");d.innerHTML="Loading...";d.style.color="white";d.style.position="absolute";d.style.fontFamily="sans-serif";d.style.top=0.45*b+"px";d.style.left=0.5*a-30+"px";c.loading=d;c.appendChild(d);this.hotspotOverlay=c},loadHotspotImage:function(a){var b=document.createElement("img");b.data=a;b.onload=this.hotspotImageLoaded.apply(this,[b]);b.onerror=this.hotspotImageError.apply(this,[b]);b.src=this.path+a.src},hotspotImageError:function(a){return function(){alert("Error loading image:"+
a.src)}},hotspotImageLoaded:function(a){var b=this;return function(){b.target.appendChild(a);a.style.display="block";a.style.position="absolute";a.style.top="0px";a.style.left="0px";a.style.cursor="pointer";a.style.zIndex=b.zIndex.hotspotImage;this.relativeY=this.relativeX=0.5;b.fitHotspotImageToTarget(a);b.hotspotImage=a;a.data.title&&b.addHotspotTitle(a.data);RotateTool.addClickOrTouchListener(a,RotateTool.eventsTouchEnd,RotateTool.bind(b,b.hideImageHotspot))}},fitHotspotImageToTarget:function(a){var b=
1,c=a.width,b=a.height,b=this.targetRatio<c/b?this.targetWidth/c:this.targetHeight/b,c=Math.floor(a.height*b),b=Math.floor(a.width*b);a.height=c;a.width=b;a.width<this.targetWidth&&(a.style.left=Math.floor(0.5*(this.targetWidth-b))+"px",a.style.top="0px");a.height<this.targetHeight&&(a.style.top=Math.floor(0.5*(this.targetHeight-c))+"px",a.style.left="0px")},addHotspotTitle:function(a){var b=document.createElement("div");b.innerHTML=a.title;b.style.zIndex=this.zIndex.hotspotTitle;b.style.position=
"absolute";b.style.left="0px";b.style.bottom="0px";b.style.fontFamily="sans-serif";b.style.color="white";b.style.backgroundColor="#000000";b.style.textAlign="left";b.style.padding="10px";b.style.opacity="0.75";b.style.fontSize="18px";b.style.width=this.targetWidth+"px";this.hotspotTitle=b;this.target.appendChild(b)},hideImageHotspot:function(){this.target.removeChild(this.hotspotImage);this.target.removeChild(this.hotspotOverlay);this.target.removeChild(this.hotspotTitle)},redrawHotspots:function(){if(null!==
this.hotspotInstances&&(this.hideAllHotspots(),this.currentImage)){this.showFixedHotspots();var a=this.currentImage.hotspots;if(null!==a)for(var b=0;b<a.length;b++)this.showHotspot(a[b])}},hideAllHotspots:function(){for(var a in this.hotspotInstances)this.hotspotInstances[a].style.display="none"},showFixedHotspots:function(){var a,b,c;for(c in this.hotspotInstances)if(this.hotspotInstances[c].isFixed)if(a=this.hotspotInstances[c].data.levels)for(this.hotspotInstances[c].style.display="none",b=0;b<
a.length;b++){if(a[b]==this.lastImgV){this.hotspotInstances[c].style.display="block";break}}else this.hotspotInstances[c].style.display="block"},showHotspot:function(a){var b=this.hotspotInstances[a.id];if(b&&!b.isFixed){b.style.display="block";var c,d;b.image?(c=b.image.width,d=b.image.height):(c=b.offsetWidth,d=b.offsetHeight);b.isFixed||(c=this.currentImage.offsetLeft+a.rx*this.currentImage.width-0.5*c,b.style.top=Math.floor(this.currentImage.offsetTop+a.ry*this.currentImage.height-0.5*d)+"px",
b.style.left=Math.floor(c)+"px")}},startRotation:function(){this.dispatchEvent(RotateTool.ROTATION_START);0==this.dx&&(this.dx=0!=this.previousDx?this.previousDx:0>this.settings.rotation.rotateDirection?-1:1);this.rotateInterval&&clearInterval(this.rotateInterval);this.rotateInterval=setInterval(RotateTool.bind(this,this.showNextImage),this.rotateIntervalDuration);this.isRotating=!0},stopRotation:function(){this.isRotating&&(this.dispatchEvent(RotateTool.ROTATION_STOP),clearInterval(this.rotateInterval),
this.isRotating=!1,this.previousDx=this.dx)},showNextImage:function(){this.requestRescaleFlag&&this.setRescaleFlag();null==this.lastImgH?this.newImgV=this.newImgH=0:(this.newImgH=this.lastImgH+this.dx,this.newImgV=this.lastImgV+this.dy);this.newImgH>=this.hSteps&&(this.newImgH=0,this.settings.rotation.bounce&&(this.newImgH=this.hSteps-1,this.dx=-this.dx));0>this.newImgH&&(this.newImgH=this.hSteps-1,this.settings.rotation.bounce&&(this.newImgH=0,this.dx=-this.dx));this.newImgV>=this.vSteps&&(this.newImgV=
this.vSteps-1);0>this.newImgV&&(this.newImgV=0);this.previousImage=this.currentImage;this.currentImage=this.rotateImages[this.imagesGrid[this.newImgV][this.newImgH]];this.dispatchEvent(RotateTool.ON_IMAGE,{imgH:this.newImgH,imgV:this.newImgV,imgSrc:this.currentImage.src,fileName:this.currentImage.fileName});this.setScale(this.scaleInPercent,this.currentImage);this.previousImage&&(this.previousImage.style.visibility="hidden");this.currentImage&&(this.currentImage.style.visibility="visible");this.redrawHotspots();
this.lastImgH=this.newImgH;this.lastImgV=this.newImgV;this.settings.rotation.rotateOnce&&(this.rotateOnceCounter++,this.rotateOnceCounter==this.hSteps+1&&this.stopRotation())},setScale:function(a,b){if(b&&(a=Math.max(100,a),this.scaleInPercent=a=Math.min(a,this.settings.control.maxZoom),!b.scaled)){var c=1,c=this.targetRatio<b.ratio?this.targetWidth/b.originalWidth:this.targetHeight/b.originalHeight,c=c*(a/100),d;d=Math.floor(b.originalHeight*c);c=Math.floor(b.originalWidth*c);b.style.height=d+"px";
b.style.width=c+"px";100<a?(c=-this.relativeX*c+0.5*this.targetWidth,d=-this.relativeY*d+0.5*this.targetHeight,b.style.top=""+d+"px",b.style.left=""+c+"px"):(this.relativeY=this.relativeX=0.5,c<this.targetWidth&&d<this.targetHeight&&(b.style.top=Math.floor(0.5*(this.targetHeight-d))+"px",b.style.left=Math.floor(0.5*(this.targetWidth-c))+"px"),c==this.targetWidth&&d==this.targetHeight&&(b.style.left="0px",b.style.top="0px"),c<this.targetWidth&&d==this.targetHeight&&(b.style.left=Math.floor(0.5*(this.targetWidth-
c))+"px",b.style.top="0px"),c==this.targetWidth&&d<this.targetHeight&&(b.style.top=Math.floor(0.5*(this.targetHeight-d))+"px",b.style.left="0px"));100<a||1E3<this.targetWidth?b.srcLarge&&b.src!=b.srcLarge&&(b.onload=null,b.src=b.srcLarge):b.src==b.srcLarge&&(b.src=b.srcNormal);b.scaled=!0;b.correctLeft=b.style.left;this.redrawHotspots()}},setRescaleFlag:function(){for(var a=0;a<this.rotateImages.length;a++)this.rotateImages[a].scaled=!1;this.requestRescaleFlag=!1},addControls:function(){this.settings.userInterface.showTogglePlayButton&&
this.addPlayPauseButton();this.settings.userInterface.showZoomSlider&&this.addZoomSlider();this.settings.userInterface.showArrows&&this.addArrowButtons();this.settings.userInterface.showToggleFullscreenButton&&RotateTool.isFullscreenBrowserAPISupported&&RotateTool.isRunningInIframe&&this.addFullscreenButton();RotateTool.yofla_360_is_preview&&this.settings.userInterface.showToggleFullscreenButton&&this.addFullscreenButton();if("true"==this.settings.userInterface.showToggleRotateButton||!0==this.settings.userInterface.showToggleRotateButton||
"zoom"==this.settings.userInterface.showToggleRotateButton)this.addToggleRotateButton(),this.addTogglePanButton(),this.toggleRotationInZoomMode(!1),"zoom"==this.settings.userInterface.showToggleRotateButton?this.toggleToggleRotatePanButtons(!1):this.toggleToggleRotatePanButtons(!0);this.addClickPane();this.addClickPaneTouchControls()},addPlayPauseButton:function(){return this.generateButton("rotate-tool-button-play",this.playButtonClickListener)},playButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_PLAY_PAUSE_CLICK);
this.isZoomed&&this.resetZoom();this.toggleRotation()},addToggleRotateButton:function(){return this.generateButton("rotate-tool-button-toggle-rotate",this.toggleRotateButtonClickListener)},toggleRotateButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_ROTATE_CLICK);this.toggleRotationInZoomMode(!0)},addTogglePanButton:function(){return this.generateButton("rotate-tool-button-toggle-pan",this.togglePanButtonClickListener)},togglePanButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_PAN_CLICK);
this.toggleRotationInZoomMode(!1)},toggleRotationInZoomMode:function(a){var b=this.buttons["rotate-tool-button-toggle-pan"],c=this.buttons["rotate-tool-button-toggle-rotate"],d=this.buttons["rotate-tool-button-toggle-rotate"].offsetWidth,d=d?d:22;a?(this.isRotationWhenZoomed=!0,b.style.backgroundPosition="0px",c.style.backgroundPosition="-"+d+"px",this.dispatchEvent(RotateTool.TOGGLE_ROTATE_MODE)):(this.isRotationWhenZoomed=!1,b.style.backgroundPosition="-"+d+"px",c.style.backgroundPosition="0px",
this.dispatchEvent(RotateTool.TOGGLE_PAN_MODE))},addFullscreenButton:function(){return this.generateButton("rotate-tool-button-fullscreen",this.fullscreenButtonClickListener)},fullscreenButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_FULLSCREEN_CLICK);RotateTool.yofla_360_is_preview?alert("Please preview fullscreen in a browser (requires iframe embed)."):(this.isZoomed&&this.resetZoom(),RotateTool.isFullscreen()?RotateTool.exitFullscreen(this.target):RotateTool.launchFullscreen(this.target))},
addArrowButtons:function(){this.generateButton("rotate-tool-button-left",this.leftButtonClickListener);this.generateButton("rotate-tool-button-right",this.rightButtonClickListener);1<this.vSteps&&(this.generateButton("rotate-tool-button-up",this.upButtonClickListener),this.generateButton("rotate-tool-button-down",this.downButtonClickListener))},leftButtonClickListener:function(){this.dispatchEvent(RotateTool.BUTTON_ARROW_LEFT_CLICK);this.stopRotation();this.dx=1;this.settings.control.reverseDrag&&
(this.dx=-this.dx);this.showNextImage()},rightButtonClickListener:function(){this.dispatchEvent(RotateTool.BUTTON_ARROW_RIGHT_CLICK);this.stopRotation();this.dx=-1;this.settings.control.reverseDrag&&(this.dx=-this.dx);this.showNextImage()},upButtonClickListener:function(){this.resetZoom();this.stopRotation();this.dx=0;this.dy=1;this.showNextImage();this.dy=0},downButtonClickListener:function(){this.resetZoom();this.stopRotation();this.dx=0;this.dy=-1;this.showNextImage();this.dy=0},generateButton:function(a,
b){var c=document.createElement("div");c.className="rotate-tool-button "+a;c.style.zIndex=this.zIndex.buttons;c.style.position="absolute";this.target.appendChild(c);RotateTool.addClickOrTouchListener(c,{forTouch:"touchend",forMouse:"click"},RotateTool.bind(this,b));return this.buttons[a]=c},addZoomSlider:function(){var a=this,b=this.createSliderContainer(),c=this.createSliderHandle(),d=97,k=function(b){b||(b=window.event);var e=RotateTool.getMousePosition(b).x-c.mouseStartX,e=c.currentX+e,e=Math.max(0,
e),e=Math.min(d,e);isNaN(e)&&(e=0);c.style.left=e+"px";var k=e/d;c.newOffsetX=e;a.zoomRatioChangeListener(k,"sliderHandle");RotateTool.isTouchDevice&&b.preventDefault()},e=function(b){b||(b=window.event);c.currentX=c.newOffsetX;RotateTool.removeClickOrTouchListener(document,RotateTool.eventsTouchMove,k);RotateTool.removeClickOrTouchListener(document,RotateTool.eventsTouchEnd,e);a.draggedObject=null;RotateTool.isTouchDevice&&b.preventDefault()};RotateTool.addClickOrTouchListener(c,RotateTool.eventsTouchStart,
function(h){d=b.offsetWidth-c.offsetWidth;h||(h=window.event);a.draggedObject=c;a.dispatchEvent(RotateTool.BUTTON_ZOOMSLIDER_CLICK);c.mouseStartX=RotateTool.getMousePosition(h).x;RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchMove,k);RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchEnd,e);RotateTool.isTouchDevice&&h.preventDefault()});b.appendChild(c);this.target.appendChild(b);this.sliderHandle=c;this.handleMaxX=d},createSliderContainer:function(){var a=document.createElement("div");
a.className="rotate-tool-zoomslider";a.style.zIndex=this.zIndex.buttons;a.style.position="absolute";return a},createSliderHandle:function(){var a=document.createElement("div");a.className="rotate-tool-zoomslider-handle";a.style.position="absolute";a.currentX=0;return a},updateSliderHandlePosition:function(a){this.sliderHandle&&(this.sliderHandle.style.left=Math.floor(a*this.handleMaxX)+"px")},addClickPane:function(){var a=document.createElement("div");a.style.width="100%";a.style.height="100%";a.style.background=
"white";a.style.opacity="0";a.style.filter="alpha(Opacity=0)";a.style.display="block";a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.cursor="pointer";a.style.zIndex=this.zIndex.clickPane;this.target.appendChild(a);this.clickPane=a},addClickPaneTouchControls:function(){RotateTool.addClickOrTouchListener(this.clickPane,RotateTool.eventsTouchMove,RotateTool.bind(this,this.clickPaneMouseOrTouchMove));RotateTool.addClickOrTouchListener(this.clickPane,RotateTool.eventsTouchStart,
RotateTool.bind(this,this.clickPaneMouseOrTouchStart));RotateTool.addClickOrTouchListener(this.clickPane,RotateTool.eventsTouchEnd,RotateTool.bind(this,this.clickPaneMouseOrTouchEnd));RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchEnd,RotateTool.bind(this,this.clickPaneMouseOrTouchEnd));this.settings.control.rotateOnMouseHover&&!RotateTool.isTouchDevice&&this.addRotateOnHoverActions();this.clickPane.addEventListener?(this.clickPane.addEventListener("mousewheel",RotateTool.bind(this,
this.MouseWheelHandler),!1),this.clickPane.addEventListener("DOMMouseScroll",RotateTool.bind(this,this.MouseWheelHandler),!1)):this.clickPane.attachEvent("onmousewheel",RotateTool.bind(this,this.MouseWheelHandler))},clickPaneMouseOrTouchStart:function(a){a=a||window.event;this.hideContexMenu();this.wasRotating=this.isRotating;this.stopRotation();if(a.button&&2==a.button)return a.preventDefault&&a.preventDefault(),!1;this.isTouchOrMouseDown=!0;this.touchMovePreviousDrag=this.touchMovePrevious=this.touchMove=
this.touchStart=RotateTool.getMousePosition(a);this.currentImage.startOffsetX=parseInt(this.currentImage.style.left,10);this.currentImage.startOffsetY=parseInt(this.currentImage.style.top,10);this.startDragListener(this.touchMove);this.hideInfoPanel();this.isZoomed?this.isRotationWhenZoomed?this.dispatchEvent(RotateTool.TURN_START,this.lastImgH):this.dispatchEvent(RotateTool.PAN_START,this.lastImgH):this.dispatchEvent(RotateTool.TURN_START,this.lastImgH);RotateTool.isTouchDevice&&a.preventDefault()},
clickPaneMouseOrTouchMove:function(a){!1!=this.isTouchOrMouseDown&&(this.touchMove=RotateTool.getMousePosition(a),this.evalClickPaneTouchMove(this.touchStart,this.touchMove),this.touchMovePrevious=this.touchMove,RotateTool.isTouchDevice&&a.preventDefault())},clickPaneMouseOrTouchEnd:function(a){if(!1!=this.isTouchOrMouseDown){this.isTouchOrMouseDown=!1;this.touchEnd=RotateTool.getMousePosition(a);var b=this.evalClickPaneTouchEnd(this.touchStart,this.touchEnd);this.stopDragListener();!1===b&&(100==
this.scaleInPercent?this.dispatchEvent(RotateTool.TURN_STOP,this.lastImgH):this.isRotationWhenZoomed?this.dispatchEvent(RotateTool.TURN_STOP,this.lastImgH):this.dispatchEvent(RotateTool.PAN_STOP,this.lastImgH));this.settings.control.rotateOnMouseHover&&!1==RotateTool.isTouchDevice&&!1==this.isRotating&&this.clickPaneMouseOrTouchStart(a)}},addRotateOnHoverActions:function(){this.clickPane.addEventListener("mouseenter",RotateTool.bind(this,this.clickPaneMouseOver),!0);this.clickPane.addEventListener("mouseleave",
RotateTool.bind(this,this.clickPaneMouseOut),!0)},clickPaneMouseOver:function(a){this.clickPaneMouseOrTouchStart(a)},clickPaneMouseOut:function(a){this.clickPaneMouseOrTouchEnd(a)},clickPaneMouseMove:function(a){},startDragListener:function(a){this.isZoomed&&!1==this.isRotationWhenZoomed||(this.lastYatDyChange=a.y,a=this.rotateIntervalDuration*this.settings.control.dragSpeed,this.dragInterval=setInterval(RotateTool.bind(this,this.dragListener),a))},stopDragListener:function(){clearInterval(this.dragInterval)},
dragListener:function(){var a=this.touchMovePreviousDrag.y-this.touchMove.y,b=this.touchMovePreviousDrag.x-this.touchMove.x;5<Math.abs(a)&&(b=0);5<Math.abs(b)&&(a=0);b=RotateTool.signum(b);0!==b&&(this.settings.control.reverseDrag&&(b=-b),this.dx=b,this.dy=0,this.showNextImage());1<this.vSteps&&this.lastYatDyChange&&(b=0,Math.abs(this.touchMove.y-this.lastYatDyChange)>this.settings.rotation.multilevel.verticalSensitivity&&(b=RotateTool.signum(a),this.lastYatDyChange=this.touchMove.y,this.dy=b,this.dx=
0,this.showNextImage()));this.touchMovePreviousDrag=this.touchMove},evalClickPaneTouchEnd:function(a,b){var c=!1;if(b&&a){var d=Math.abs(b.x-a.x),k=Math.abs(b.y-a.y);1>=d+k&&(this.evalClickOnPane(),c=!0);return c}},evalClickPaneTouchMove:function(a,b){if(this.isZoomed&&this.isTouchOrMouseDown){var c=b.x-a.x,d=b.y-a.y;if(!this.isRotationWhenZoomed&&(c=this.currentImage.startOffsetX+c,d=this.currentImage.startOffsetY+d,this.currentImage))try{this.currentImage.style.left=c+"px",this.currentImage.style.top=
d+"px",this.relativeX=-(c-0.5*this.targetWidth)/parseInt(this.currentImage.style.width),this.relativeY=-(d-0.5*this.targetHeight)/parseInt(this.currentImage.style.height)}catch(k){}this.redrawHotspots()}},evalClickOnPane:function(){this.dispatchEvent(RotateTool.CLICK_OBJECT);this.isZoomed?(this.resetZoom(),this.startRotation()):this.settings.control.clickUrl?(this.stopRotation(),this.openClickUrl()):(this.isRotating=this.wasRotating,this.toggleRotation())},openClickUrl:function(){var a=this.settings.control.clickUrl,
b=this.settings.control.clickUrlTarget;a&&(b||(b="_top"),window.open(a,b))},MouseWheelHandler:function(a){a=window.event||a;var b=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail));try{a.preventDefault()}catch(c){}this.settings.control.mouseWheelZooms||a.ctrlKey||a.metaKey?(a=this.settings.control.maxZoom,this.stopRotation(),this.zoomRatioChangeListener(1/(a-100)*(this.scaleInPercent-10*b)-100*(1/(a-100)),"mouseWheel")):(!0!==this.toolTipOnMouseWheelShown&&!1==RotateTool.isTouchDevice&&(a=RotateTool.getLocalMousePosition(a),
this.showToolTip([a.x,a.y],"Tip: use MouseWheel+Ctrl for Zooming",3E3),this.toolTipOnMouseWheelShown=!0),this.stopRotation(),this.dx=b,this.mouseWheelCounter++,0==this.mouseWheelCounter%4&&this.showNextImage())},toggleRotation:function(){this.isRotating?this.stopRotation():this.startRotation()},windowResizeListener:function(a){this.hideInfoPanel();this.stopRotation();this.resetZoom();this.updateTargetStyles();this.setTargetDimensions();this.currentImage&&(this.currentImage.scaled=!1);this.setScale(100,
this.currentImage);this.requestRescaleFlag=!0},zoomRatioChangeListener:function(a,b){this.stopRotation();a=Math.max(0,a);a=Math.min(1,a);var c=100+(this.settings.control.maxZoom-100)*a;this.dispatchEvent(RotateTool.ZOOM_CHANGE,this.lastImgH);0==a&&this.dispatchEvent(RotateTool.ZOOM_RESET,this.lastImgH);this.currentImage&&(this.currentImage.scaled=!1,this.setScale(c,this.currentImage),this.currentImage.scaled=!1);this.requestRescaleFlag=!0;this.isZoomed=0!==a;"sliderHandle"!=b&&this.updateSliderHandlePosition(a);
"zoom"==this.settings.userInterface.showToggleRotateButton&&this.toggleToggleRotatePanButtons(0!=a)},toggleToggleRotatePanButtons:function(a){this.buttons["rotate-tool-button-toggle-pan"]&&(a?(this.buttons["rotate-tool-button-toggle-pan"].style.display="block",this.buttons["rotate-tool-button-toggle-rotate"].style.display="block"):(this.buttons["rotate-tool-button-toggle-pan"].style.display="none",this.buttons["rotate-tool-button-toggle-rotate"].style.display="none"))},resetZoom:function(){this.zoomRatioChangeListener(0,
null)},reportBrowserNotSupported:function(){this.target.innerHTML='<span class="rotate-tool-browser-not-supported">Your browser does not support this 3D Object rotation script.</span>'},addPlayerInfo:function(){var a=document.createElement("div"),b=document.createElement("a");b.href="http://www.yofla.com/3d-rotate/player-about/";b.target="_blank";b.innerHTML="360 by YoFLA";b.style.textDecoration="none";b.style.color="navy";b.style.fontFamily="sans-serif";b.style.fontSize="10px";b.style.paddingLeft=
"5px";b.style.paddingRight="5px";a.appendChild(b);this.target.appendChild(a);a.style.position="absolute";a.style.top="2px";a.style.right="4px";a.style.zIndex=this.zIndex.info+1;a.style.background="white";a.style.borderRadius="5px";a.style.opacity=0.75;a.style.filter="alpha(Opacity=75)";setInterval(function(){a.style.display="none"},5500)},addEventListener:function(a,b,c){c="undefined"===typeof c?!1:c;!1===RotateTool.isCustomEventSupported?document.addEventListener(a,b,c):this.target.addEventListener(a,
b,c)},dispatchEvent:function(a,b){this.detectZoomStart(a);this.isGAenabled&&this.reportGAevent(a,b);if(!1===RotateTool.isCustomEventSupported)try{var c=document.createEvent("Event");c.initEvent(a,!0,!0);c.detail=b;document.dispatchEvent(c)}catch(d){}else c=new CustomEvent(a,{detail:b}),this.target.dispatchEvent(c)},detectZoomStart:function(a){a==RotateTool.ZOOM_CHANGE&&this.lastEventName!=RotateTool.ZOOM_CHANGE&&this.dispatchEvent(RotateTool.ZOOM_START);this.lastEventName=a},reportGAevent:function(a,
b){if(!1!=RotateTool.isGAloaded(this.gaTrackingId)&&0<=this.gaEnabledEvents.indexOf(a)){var c=this.gaCategory,d=this.gaLabel;!0==isNaN(b)?ga("send","event",c,a,d):ga("send","event",c,a,d,parseInt(b))}},rotateToolInstanceLast:"no colon"};d.initialize();return d},fixPathVariable:function(a){if(a&&0<a.length){var d=a.substr(a.length-1);"/"!=d&&"\\"!=d&&(a+="/")}else a="";return a},loadScript:function(a,d,f){var b=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript";
c.onreadystatechange=function(){if("loaded"===c.readyState||"complete"===c.readyState)c.onreadystatechange=null,d.apply(f)};c.onload=function(){d.apply(f)};c.src=a;b.appendChild(c)},parseJSON:function(a){if("string"!==typeof a||!a)return null;if(window.JSON&&window.JSON.parse)return window.JSON.parse(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return(new Function("return "+
a))();throw"Invalid JSON: "+a;},addEventSimple:function(a,d,f){a.addEventListener?a.addEventListener(d,f,!1):a.attachEvent&&a.attachEvent("on"+d,f)},removeEventSimple:function(a,d,f){a.removeEventListener?a.removeEventListener(d,f,!1):a.detachEvent&&a.detachEvent("on"+d,f)},getMousePosition:function(a){if("undefined"===typeof a)return null;var d={x:null,y:null};a.changedTouches?(d.x=a.changedTouches[0].screenX,d.y=a.changedTouches[0].screenY):(d.x=a.clientX,d.y=a.clientY);return d},getLocalMousePosition:function(a){a=
a||window.event;var d=a.target||a.srcElement;d.currentStyle||window.getComputedStyle(d,null);d=d.getBoundingClientRect();return{x:a.clientX-d.left,y:a.clientY-d.top}},defaultPreloader:function(a,d){var f=this,b={percentDiv:null,targetDiv:null,initialize:function(a){this.targetDiv=document.getElementById(a);this.backgroundDiv=document.createElement("div");this.backgroundDiv.style.left="0px";this.backgroundDiv.style.zIndex=f.zIndex.preloader;this.backgroundDiv.style.position="absolute";this.backgroundDiv.style.top=
Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.backgroundDiv.style.width="100%";this.backgroundDiv.style.height="50px";this.backgroundDiv.style.backgroundColor="#ffffff";this.backgroundDiv.style.opacity=0.5;this.backgroundDiv.style.filter="alpha(Opacity=50)";this.targetDiv.appendChild(this.backgroundDiv);this.progressBar=document.createElement("div");this.progressBar.style.left="0px";this.progressBar.style.zIndex=f.zIndex.preloader;this.progressBar.style.position="absolute";this.progressBar.style.top=
Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.progressBar.style.width="0%";this.progressBar.style.height="50px";this.progressBar.style.backgroundColor="#909090";this.progressBar.style.opacity=0.5;this.progressBar.style.filter="alpha(Opacity=50)";this.targetDiv.appendChild(this.progressBar);this.percentDiv=document.createElement("div");this.percentDiv.style.fontSize="32px";this.percentDiv.style.fontFamily="verdana, arial, sans-serif";this.percentDiv.style.lineHeight="50px";this.percentDiv.style.textAlign=
"center";this.percentDiv.style.width="100%";this.percentDiv.style.top=Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.percentDiv.style.zIndex=f.zIndex.preloader+1;this.percentDiv.style.position="absolute";this.percentDiv.style.color=d;this.percentDiv.style.opacity=1;this.percentDiv.style.filter="alpha(Opacity=100)";this.percentDiv.innerHTML="&nbsp; 0%";this.percentDiv.setAttribute("id","preloader_"+this.targetDiv.id);this.targetDiv.appendChild(this.percentDiv)},update:function(a){var b="";
10>a&&(b="&nbsp; ");this.percentDiv&&(this.percentDiv.innerHTML=b+a+"%");this.progressBar&&(this.progressBar.style.width=a+"%")},destroy:function(){this.percentDiv.innerHTML="";this.percentDiv.style.display="none";this.targetDiv.removeChild(this.percentDiv);this.targetDiv.removeChild(this.backgroundDiv);this.targetDiv.removeChild(this.progressBar);this.targetDiv=this.percentDiv=this.progressBar=this.backgroundDiv=null}};b.initialize(a);return b},wavePreloader:function(a,d){var f=this,b={percentDiv:null,
targetDiv:null,initialize:function(a,b){this.targetDiv=document.getElementById(a);this.backgroundDiv=document.createElement("div");this.backgroundDiv.style.left="0px";this.backgroundDiv.style.zIndex=f.zIndex.preloader;this.backgroundDiv.style.position="absolute";this.backgroundDiv.style.top=Math.round(this.targetDiv.offsetHeight/2)-33+"px";this.backgroundDiv.style.width="100%";this.backgroundDiv.style.height="50px";this.backgroundDiv.style.backgroundColor="#ffffff";this.backgroundDiv.style.opacity=
0.5;this.backgroundDiv.style.filter="alpha(Opacity=50)";this.targetDiv.appendChild(this.backgroundDiv);this.percentDiv=document.createElement("div");this.percentDiv.style.zIndex=f.zIndex.preloader+1;this.percentDiv.style.position="relative";var d;d=""+('<div class="yp_wave" style="margin-top: '+(Math.floor(0.5*this.targetDiv.clientHeight)-20)+'px;">');d=d+('\t<div class="rect1" style="background-color: '+b+'"></div>')+('\t<div class="rect2" style="background-color: '+b+'"></div>');d+='\t<div class="rect3" style="background-color: '+
b+'"></div>';d+='\t<div class="rect4" style="background-color: '+b+'"></div>';d+='\t<div class="rect5" style="background-color: '+b+'"></div>';d+="</div>";this.percentDiv.innerHTML=d;this.percentDiv.setAttribute("id","preloader_"+this.targetDiv.id);this.targetDiv.appendChild(this.percentDiv)},update:function(a){},destroy:function(){this.percentDiv.innerHTML="";this.percentDiv.style.display="none";this.targetDiv.removeChild(this.percentDiv);this.targetDiv.removeChild(this.backgroundDiv);this.targetDiv=
this.percentDiv=this.backgroundDiv=null}};b.initialize(a,d);return b},addClickOrTouchListener:function(a,d,f){this.isTouchDevice?void 0!==d.forTouch&&this.addEventSimple(a,d.forTouch,f):void 0!==d.forMouse&&this.addEventSimple(a,d.forMouse,f)},removeClickOrTouchListener:function(a,d,f){this.isTouchDevice?this.removeEventSimple(a,d.forTouch,f):this.removeEventSimple(a,d.forMouse,f)},bind:function(a,d){return function(){d.apply(a,arguments)}},signum:function(a){return 0<a?1:0>a?-1:0},supportedBrowserCheck:function(){return/MSIE (\d+\.\d+);/.test(navigator.userAgent)?
8<=Number(RegExp.$1):!0},fullscreenBrowserCheck:function(){return document.body.requestFullscreen?!0:document.body.mozRequestFullScreen?!0:document.body.webkitRequestFullscreen?!0:document.body.msRequestFullscreen?!0:!1},browserSupportsCSSProperty:function(a){var d=document.createElement("div");a=a.toLowerCase();if(void 0!=d.style[a])return!0;a=a.charAt(0).toUpperCase()+a.substr(1);for(var f=["Webkit","Moz","ms","O"],b=0;b<f.length;b++)if(void 0!=d.style[f[b]+a])return!0;return!1},isObjectEmpty:function(a){if(void 0===
a)return!0;var d=Object.prototype.hasOwnProperty;if(a.length&&0<a.length)return!1;if(a.length&&0===a.length)return!0;for(var f in a)if(d.call(a,f))return!1;return!0},launchFullscreen:function(a){a.requestFullscreen?a.requestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():a.msRequestFullscreen&&a.msRequestFullscreen()},exitFullscreen:function(a){document.cancelFullscreen?document.cancelFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.webkitCancelFullScreen?document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen()},isFullscreen:function(){return!!(document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement)},isInIframe:function(){try{return window.self!==window.top}catch(a){return!0}},addGlobalFunctions:function(){window.yofla_setColor=this.yofla_setColor;window.yofla_setLevel=this.yofla_setColor},yofla_setColor:function(a){var d,
f=0;"string"===typeof a?0<=a.indexOf(",")?(f=a.split(","),d=f[0],f=f[1]):f=parseInt(a):f=parseInt(a);(d=RotateTool.get(d))?d.setLevel(f):alert("Unable to locate 3DRT instance!")},detectCustomEventSupport:function(){try{return new CustomEvent,!0}catch(a){return!1}},baseName:function(a){var d=a.charAt(a.length-1);if("/"===d||"\\"===d)a=a.slice(0,-1);a=a.replace(/^.*[\/\\]/g,"");"string"===typeof suffix&&a.substr(a.length-suffix.length)==suffix&&(a=a.substr(0,a.length-suffix.length));return a},isGAloaded:function(a){if("function"===
typeof ga)return!0;if("undefined"!==typeof a&&!0!==this.gaCodeWritten){var d="auto";"localhost"==document.location.hostname&&(d={cookieDomain:"none"});(function(a,b,c,d,k,e,h){a.GoogleAnalyticsObject=k;a[k]=a[k]||function(){(a[k].q=a[k].q||[]).push(arguments)};a[k].l=1*new Date;e=b.createElement(c);h=b.getElementsByTagName(c)[0];e.async=1;e.src=d;h.parentNode.insertBefore(e,h)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create",a,d);this.gaCodeWritten=!0}return!1},
addPolyFills:function(){this.addIndexOf()},addIndexOf:function(){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,d){var f=this.length>>>0,b=Number(d)||0,b=0>b?Math.ceil(b):Math.floor(b);for(0>b&&(b+=f);b<f;b++)if(b in this&&this[b]===a)return b;return-1})},getCurrentDomain:function(){var a=window.location!=window.parent.location?document.referrer:document.location,d=document.createElement("a");d.href=a;return(a=d.hostname)&&3<a.length?a=a.replace(/^www\./,""):""},last:"none"};RotateTool.initialize();
